"""add payments table

Revision ID: 69254a568007
Revises: 495024a1ed6f
Create Date: 2026-06-22 22:54:56.293976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69254a568007'
down_revision: Union[str, Sequence[str], None] = '495024a1ed6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('payments_order_code_key'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_order_code'), 'payments', ['order_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_code'), table_name='payments')
    op.create_unique_constraint(op.f('payments_order_code_key'), 'payments', ['order_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('payments', 'checkout_url')
    # ### end Alembic commands ###
