"""add score column

Revision ID: 6eae4e585e6a
Revises: 3e000130eaee
Create Date: 2026-06-16 22:39:44.875544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eae4e585e6a'
down_revision: Union[str, Sequence[str], None] = '3e000130eaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('uploaded_files', sa.Column('status', sa.String(), nullable=True))
    op.add_column('uploaded_files', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('uploaded_files', sa.Column('total_errors', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_column('uploaded_files', 'total_errors')
    op.drop_column('uploaded_files', 'score')
    op.drop_column('uploaded_files', 'status')
    op.drop_column('uploaded_files', 'user_id')
    # ### end Alembic commands ###
